/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManage;

import com.toedter.calendar.JCalendar;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mizanur Rahman
 */
public class Add_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Add_Employee
     */
    public Add_Employee() {
        initComponents();
        Toolkit t1=Toolkit.getDefaultToolkit();
        int w=(int)t1.getScreenSize().getWidth();
        int h=(int)t1.getScreenSize().getHeight();
        this.setSize(w, h);
        dateSet();
       
        ShowData();
        txtid.requestFocus();
        txtid.setText(""+autoid());
    }

     Connection con=null;
    ResultSet rs=null;
    Statement st=null;
    PreparedStatement pst=null;
    void Myconnect(){
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","");
        } catch (SQLException ex) {
            Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void Myconnection1(){
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","");
            st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void dateSet(){
       JCalendar d=new JCalendar();
         SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            String mm=sd.format(d.getDate());
        ((JTextField)txtdate.getDateEditor().getUiComponent()).setText(mm);
        
    }
    
    void ShowData(){
        try {
            Myconnect();
            DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
             String m="SELECT *FROM `employee`";
            pst=con.prepareCall(m);
            rs=pst.executeQuery();
            while(rs.next()){
                dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Add_Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    int autoid(){
        int a=0;
        try {
            Myconnect();
            String m="SELECT `id` FROM `employee` ORDER BY `id` ASC";
            pst=con.prepareCall(m);
           rs=pst.executeQuery();
           while(rs.next()){
               a=rs.getInt(1);
           }
           a++;
           
            
        } catch (SQLException ex) {
            Logger.getLogger(Add_Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
      return a;  
    }
    void Cl_panel(){
       txtid.setText("");
       txtname.setText("");
       txtemail.setText("");
       txtcon.setText("");
       txtacc.setText("");
       txtdesig.setSelectedIndex(0);
       txtsal.setText("");
       dateSet();
       txtad.setText("");
        txtid.setText(""+autoid());
    }
    void SelectedTablevaluesetTable(String x){
        int p=0;
       int a=txtdesig.getItemCount();
        for (int i = 0; i !=a; i++) {
            String m=txtdesig.getItemAt(i).toString();
            if(m.contains(x))
            {
               p=i; 
                
            }
            
        }
        txtdesig.setSelectedIndex(p);
       
        
        
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtad = new javax.swing.JTextField();
        txtcon = new javax.swing.JTextField();
        txtsal = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtacc = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtdesig = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 230, 18, 19);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        getContentPane().add(txtemail);
        txtemail.setBounds(140, 380, 250, 40);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 270, 43, 19);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Designation:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 88, 19);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 350, 62, 19);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 390, 41, 19);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Account No:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 430, 84, 19);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact No:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 470, 81, 19);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Salary");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 550, 60, 19);

        txtad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadActionPerformed(evt);
            }
        });
        txtad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtadKeyReleased(evt);
            }
        });
        getContentPane().add(txtad);
        txtad.setBounds(140, 340, 250, 40);

        txtcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconActionPerformed(evt);
            }
        });
        txtcon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtconKeyReleased(evt);
            }
        });
        getContentPane().add(txtcon);
        txtcon.setBounds(140, 460, 250, 40);

        txtsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalActionPerformed(evt);
            }
        });
        txtsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsalKeyReleased(evt);
            }
        });
        getContentPane().add(txtsal);
        txtsal.setBounds(140, 540, 250, 40);

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(140, 220, 250, 40);

        txtacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccActionPerformed(evt);
            }
        });
        txtacc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaccKeyReleased(evt);
            }
        });
        getContentPane().add(txtacc);
        txtacc.setBounds(140, 420, 250, 40);

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(140, 260, 250, 40);

        txtdesig.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtdesig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Font Desk Clarks", "Porters", "House Keeping", "Kithchen Staff", "Room Service", "Waiter", "Manager", "Accounter" }));
        getContentPane().add(txtdesig);
        txtdesig.setBounds(140, 300, 250, 40);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 510, 32, 19);
        getContentPane().add(txtdate);
        txtdate.setBounds(140, 500, 250, 40);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Symbol", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 180, 400, 420);

        jPanel2.setBackground(new java.awt.Color(102, 144, 208));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Employee details");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(500, 20, 470, 40);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/logso.jpg"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(120, 10, 140, 120);

        txtsearch.setBackground(new java.awt.Color(102, 144, 208));
        txtsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(255, 255, 255));
        txtsearch.setText("Search");
        txtsearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtsearch.setOpaque(false);
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtsearchMouseExited(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });
        jPanel2.add(txtsearch);
        txtsearch.setBounds(580, 90, 270, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_search_30px_5.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(550, 80, 50, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1500, 150);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_erase_20px_1.png"))); // NOI18N
        jButton1.setText("clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 660, 120, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_cancel_20px.png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 660, 120, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_delete_bin_20px_2.png"))); // NOI18N
        jButton4.setText("delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 620, 120, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_add_20px_2.png"))); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 620, 120, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_update_20px_2.png"))); // NOI18N
        jButton5.setText("update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(150, 620, 120, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_show_property_20px_2.png"))); // NOI18N
        jButton6.setText("show");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 660, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Designation", "Address", "Email", "Account No", "Contact No", "Date", "Salary"
            }
        ));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 190, 930, 490);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/sara-dubler-Koei_7yYtIo-unsplash (2).jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 140, 1500, 650);

        setBounds(0, 0, 1516, 792);
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadActionPerformed

    private void txtadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadKeyReleased

    private void txtconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconActionPerformed

    private void txtconKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconKeyReleased

    private void txtsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalActionPerformed

    private void txtsalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalKeyReleased

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyReleased

    private void txtaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccActionPerformed

    private void txtaccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccKeyReleased

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        // TODO add your handling code here:
        txtsearch.setText("");
    }//GEN-LAST:event_txtsearchMouseClicked

    private void txtsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseEntered
        // TODO add your handling code here:
        //txtsearch.setText("");
    }//GEN-LAST:event_txtsearchMouseEntered

    private void txtsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseExited
        // TODO add your handling code here:
        txtsearch.setText("Search");
    }//GEN-LAST:event_txtsearchMouseExited

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           try {
            Myconnect();
            DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            String id=txtsearch.getText().toString();
             String m="SELECT *FROM `employee` where `id`=?";
            pst=con.prepareCall(m);
            pst.setString(1, id);
            rs=pst.executeQuery();
            while(rs.next()){
                dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Add_Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
              
         
           
       }
    }//GEN-LAST:event_txtsearchKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       // dataadd();
        Cl_panel();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            Myconnect();
            String id=txtid.getText().toString();
            String m="DELETE FROM `employee`WHERE `id`=?";
            pst=con.prepareCall(m);
            pst.setString(1, id);
            int a=pst.executeUpdate();
            if(a>0){

                JOptionPane.showMessageDialog(this, "Delete Succesfult");
                ShowData();
                Cl_panel();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cutomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NumberFormatException n){
            txtid.requestFocus();
            JOptionPane.showMessageDialog(this, "Please!Give Id number.");

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            dateSet();
            Myconnect();
            String id=txtid.getText().toString();
            String name=txtname.getText().toString();
            String desig=txtdesig.getSelectedItem().toString();
            String ad=txtad.getText().toString();
            String email=txtemail.getText().toString();
            String acc=txtacc.getText().toString();
            String cont=txtcon.getText().toString();
            String date=((JTextField)txtdate.getDateEditor().getUiComponent()).getText();
            String sal=txtsal.getText().toString();
            String m="INSERT INTO `employee`(`id`,`name`,`designation`,`address`,`email`,`account`,`contact`,`date`,`salary`) VALUES (?,?,?,?,?,?,?,?,?)";
            pst=con.prepareCall(m);
            pst.setString(1, id);
             pst.setString(2, name);
             pst.setString(3, desig);
             pst.setString(4, ad);
             pst.setString(5, email);
             pst.setString(6, acc);
             pst.setString(7, cont);
             pst.setString(8, date);
             pst.setString(9, sal);
             int a=pst.executeUpdate();
             if(a>0){

                JOptionPane.showMessageDialog(this, "Added Succesfull");
                Cl_panel();
               
                ShowData();
            }
             else{
                 JOptionPane.showMessageDialog(this, "Cannot Added!");
             }
            
        } catch (SQLException ex) {
            Logger.getLogger(Add_Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(Exception cr){
            JOptionPane.showMessageDialog(this, "Enter data");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Update data
          try {
            // TODO add your handling code here:
            //dateSet();
            Myconnection1();
            String id=txtid.getText().toString();
            String name=txtname.getText().toString();
            String desig=txtdesig.getSelectedItem().toString();
            String ad=txtad.getText().toString();
            String email=txtemail.getText().toString();
            String acc=txtacc.getText().toString();
            String cont=txtcon.getText().toString();
           // String date=((JTextField)txtdate.getDateEditor().getUiComponent()).getText();
            String sal=txtsal.getText().toString();
            String m="UPDATE `employee` SET `name`='"+name+"',`designation`='"+desig+"',`address`='"+ad+"',`email`='"+email+"',`account`='"+acc+"',`contact`='"+cont+"',`salary`='"+sal+"' WHERE `id`='"+id+"'";
            
           /* pst.setString(1, id);
             pst.setString(2, name);
             pst.setString(3, desig);
             pst.setString(4, ad);
             pst.setString(5, email);
             pst.setString(6, acc);
             pst.setString(7, cont);
             pst.setString(8, date);
             pst.setString(9, sal);*/
             int a=st.executeUpdate(m);
             if(a>0){

                JOptionPane.showMessageDialog(this, "Update Succesfull");
                Cl_panel();
               
                ShowData();
            }
             else{
                 JOptionPane.showMessageDialog(this, "Cannot Update!");
             }
            
        } catch (SQLException ex) {
            Logger.getLogger(Add_Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        txtid.setText(dt.getValueAt(jTable1.getSelectedRow(),0).toString());
         txtname.setText(dt.getValueAt(jTable1.getSelectedRow(),1).toString());
         String p=dt.getValueAt(jTable1.getSelectedRow(),2).toString();
        // JOptionPane.showMessageDialog(this, p);
          SelectedTablevaluesetTable(p);
          txtad.setText(dt.getValueAt(jTable1.getSelectedRow(),3).toString());
        txtemail.setText(dt.getValueAt(jTable1.getSelectedRow(),4).toString());
        txtacc.setText(dt.getValueAt(jTable1.getSelectedRow(),5).toString());
        
        txtcon.setText(dt.getValueAt(jTable1.getSelectedRow(),6).toString());
        String y=dt.getValueAt(jTable1.getSelectedRow(),7).toString();
        ((JTextField)txtdate.getDateEditor().getUiComponent()).setText(y);
        txtsal.setText(dt.getValueAt(jTable1.getSelectedRow(),8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ShowData();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtacc;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtcon;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox txtdesig;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsal;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
