/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManage;

import com.toedter.calendar.JCalendar;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mizanur Rahman
 */
public class Cutomer extends javax.swing.JFrame {

    /**
     * Creates new form Cutomer
     */
    public Cutomer() {
        initComponents();
          Toolkit t1=Toolkit.getDefaultToolkit();
        int w=(int)t1.getScreenSize().getWidth();
        int h=(int)t1.getScreenSize().getHeight();
        this.setSize(w,h);
        comboItem();
        dateSet();
        
    }
    //Method Started
     Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    Statement st=null;
    void Myconnect(){
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","");
           
        } catch (SQLException ex) {
            Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void Myconnection1(){
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost/hotel","root","");
           st=con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(MyConnection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void comboItem(){
        try {
            txtroom.removeAllItems();
            Myconnect();
            txtroom.addItem("Select");
            
            String m="SELECT `room_no` FROM `room`";
            pst=con.prepareCall(m);
            rs=pst.executeQuery();
            while(rs.next()){
              
                txtroom.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cutomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    void Cl_panel(){
        txtidname.setSelectedIndex(0);
        txtid.setText("");
        txtname.setText("");
        txtmobile.setText("");
        male.setSelected(false);
        female.setSelected(false);
        others.setSelected(false);
        txtcountry.setText("");
        txtroom.setSelectedIndex(0);
        txtcheck.setSelectedIndex(0);
        txtdep.setText("");
        dateSet();
    }
   
    
    
    
            void dateSet(){
       JCalendar d=new JCalendar();
         SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            String mm=sd.format(d.getDate());
       jhjhjk.setText(mm);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtcountry = new javax.swing.JTextField();
        txtcheck = new javax.swing.JComboBox();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtdep = new javax.swing.JTextField();
        txtidname = new javax.swing.JComboBox();
        txtroom = new javax.swing.JComboBox();
        txtmobile = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        others = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        date1 = new javax.swing.JLabel();
        jhjhjk = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customar");
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 144, 208));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("new customer");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(440, 40, 420, 40);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/logso.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(120, 0, 140, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1490, 150);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MOBILE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 170, 130, 30);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GENDER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 210, 130, 30);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID NUMBER");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 90, 140, 40);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ROOM NO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 290, 140, 30);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NAME");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 130, 140, 30);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("COUNTRY");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 250, 140, 30);

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DATE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(120, 370, 140, 30);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ID");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 50, 140, 30);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CHECKED STATUS");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 330, 140, 30);

        txtcountry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcountry.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcountry.setCaretColor(null);
        jPanel1.add(txtcountry);
        txtcountry.setBounds(270, 250, 240, 40);

        txtcheck.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcheck.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "YES", "NO" }));
        txtcheck.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtcheck);
        txtcheck.setBounds(270, 330, 240, 40);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtid.setCaretColor(null);
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });
        jPanel1.add(txtid);
        txtid.setBounds(270, 90, 240, 40);

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtname.setCaretColor(null);
        jPanel1.add(txtname);
        txtname.setBounds(270, 130, 240, 40);

        txtdep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdep.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdep.setCaretColor(null);
        txtdep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdepKeyTyped(evt);
            }
        });
        jPanel1.add(txtdep);
        txtdep.setBounds(270, 410, 240, 40);

        txtidname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtidname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "PASSPORT", "NID", "VOTER ID", "DRIVING LICENSE" }));
        jPanel1.add(txtidname);
        txtidname.setBounds(270, 50, 240, 40);

        txtroom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtroom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtroom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtroom.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                txtroomPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(txtroom);
        txtroom.setBounds(270, 290, 240, 40);

        txtmobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmobile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtmobile.setCaretColor(null);
        txtmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmobileKeyTyped(evt);
            }
        });
        jPanel1.add(txtmobile);
        txtmobile.setBounds(270, 170, 240, 40);

        female.setText("Female");
        female.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female);
        female.setBounds(340, 210, 70, 40);

        others.setText("Others");
        others.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        others.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersActionPerformed(evt);
            }
        });
        jPanel1.add(others);
        others.setBounds(410, 210, 100, 40);

        male.setText("Male");
        male.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(270, 210, 70, 40);
        jPanel1.add(txtdate);
        txtdate.setBounds(270, 370, 240, 40);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DEPOSITE");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(120, 410, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 180, 620, 490);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_cancel_20px.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 460, 130, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_update_20px_2.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(780, 400, 130, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_add_20px_2.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 300, 130, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_delete_bin_20px_2.png"))); // NOI18N
        jButton4.setText("delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(780, 350, 130, 40);

        date1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        date1.setForeground(new java.awt.Color(204, 204, 204));
        date1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date1.setText("Today Date");
        getContentPane().add(date1);
        date1.setBounds(930, 270, 160, 40);

        jhjhjk.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jhjhjk.setForeground(new java.awt.Color(204, 204, 204));
        jhjhjk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jhjhjk);
        jhjhjk.setBounds(950, 310, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/796131d5-3dda-45c7-a3e1-cffeaa820295.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(750, 270, 360, 250);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/sara-dubler-Koei_7yYtIo-unsplash (2).jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 140, 1490, 670);

        setBounds(0, 0, 1506, 847);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        if(male.isSelected()){
            gender="Male";
            female.setSelected(false);
            others.setSelected(false);
            
        }
    }//GEN-LAST:event_maleActionPerformed

    String gender;
    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
         // TODO add your handling code here:
        if(female.isSelected()){
            gender="female";
            male.setSelected(false);
            others.setSelected(false);
        }
        
        
        
    }//GEN-LAST:event_femaleActionPerformed

    private void othersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othersActionPerformed
        // TODO add your handling code here:
          if(others.isSelected()){
              gender="others";
            male.setSelected(false);
            female.setSelected(false);
        }
       
    }//GEN-LAST:event_othersActionPerformed

    void dataadd(){
         int c=0,s=0;
        try {
           // dateSet();
              
           Myconnection1();
            mc.Myconnect();
            Myconnect();
            String  due="";
            // TODO add your handling code here:
            // JOptionPane.showMessageDialog(this, gender);
            //int idn=txtidname.getSelectedIndex();
            String idn=txtidname.getSelectedItem().toString();
            String id=txtid.getText().toString();
            String name=txtname.getText().toString();
            String mobile=txtmobile.getText().toString();
            String country=txtcountry.getText().toString();
           String room =txtroom.getSelectedItem().toString();
            String check=txtcheck.getSelectedItem().toString();
            java.util.Date dt=new java.util.Date();
        SimpleDateFormat dtm=new SimpleDateFormat("yyyy-MM-dd");
        String date=dtm.format(txtdate.getDate());
             
            int dep=Integer.parseInt(txtdep.getText());
            
            String m="SELECT `price`FROM `room` WHERE `room_no`=?";
            
            mc.pst=mc.con.prepareCall(m);
            mc.pst.setString(1, room);
           rs=mc.pst.executeQuery();
           if(rs.next()){
            
            due= rs.getString(1);
           }
            c=Integer.parseInt(due);
            //s=c-dep;
            String n="INSERT INTO `cutomer`(`id`,`id_num`,`name`,`mobile`,`gender`,`country`,`room`,`checked`,`deposite`,`room_Price`,`date`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            pst=con.prepareCall(n);
            
             pst.setString(1, idn);
            pst.setString(2, id);
           
            pst.setString(3, name);
            pst.setString(4, mobile);
             pst.setString(5, gender);
             pst.setString(6, country);
             pst.setString(7, room);
             pst.setString(8, check);
             pst.setInt(9, dep);
             pst.setInt(10, c);
             pst.setString(11, date);
             int j=pst.executeUpdate();
             if(j>0){
                 JOptionPane.showMessageDialog(this,"Added succesful");
                  // String room =txtroom.getSelectedItem().toString();
            String k="UPDATE `room` SET `availity`='Ocupied' WHERE `room_no`='"+room+"'";
            st.executeUpdate(k);
                 Cl_panel();
             }
             else{
                 JOptionPane.showMessageDialog(this, "Cann't added ");
             }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Cutomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NumberFormatException n){
            JOptionPane.showMessageDialog(this, "Please!Fill the From!");
            
        }
        catch(NullPointerException ne){
            JOptionPane.showMessageDialog(this, "Please!Select Date.");
        }
       
       
    }
    MyConnection mc=new MyConnection();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        

      
           
            dataadd();
            Cl_panel();
          
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepKeyTyped
        // TODO add your handling code here:
        
        
        char i=evt.getKeyChar();
        if(!Character.isDigit(i)){
            evt.consume();
        } else {
            
        }
        
    }//GEN-LAST:event_txtdepKeyTyped

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyReleased

    
    void find(){
        try {
            Myconnect();
            String id=txtid.getText().toString();
            String m="SELECT `id`,`name`,`mobile`,`gender`,`country`,`room`,`checked`,`deposite` FROM `cutomer` WHERE `id_num`=?";
            pst=con.prepareCall(m);
            pst.setString(1, id);
            rs=pst.executeQuery();
            while(rs.next()){
                txtidname.setSelectedItem(rs.getString(1));
                txtname.setText(rs.getString(2));
                txtmobile.setText(rs.getString(3));
                String a=rs.getString(4);
                if(a.contains("Male")){
                    male.setSelected(true);
                }
                else if(a.contains("female")){
                    female.setSelected(true);
                }
                else{
                    others.setSelected(true);
                }
                txtcountry.setText(rs.getString(5));
                txtroom.setSelectedItem(rs.getString(6));
                txtcheck.setSelectedItem(rs.getString(7));
                txtdep.setText(rs.getString(8));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cutomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            find();
            
            
            
        }
        
    }//GEN-LAST:event_txtidKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // clear
        Cl_panel();
           
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            Myconnect();
            String id=txtid.getText().toString();
            String m="DELETE FROM `cutomer` WHERE `id_num`=?";
            pst=con.prepareCall(m);
            pst.setString(1, id);
            int a=pst.executeUpdate();
            if(a>0){
                
                JOptionPane.showMessageDialog(this, "Delete Succesfult");
                Cl_panel();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cutomer.class.getName()).log(Level.SEVERE, null, ex);
        }
         catch(NumberFormatException n){
             txtid.requestFocus();
            JOptionPane.showMessageDialog(this, "Please!Give Id number.");
            
        }
       
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtroomPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_txtroomPopupMenuWillBecomeInvisible
        try {
            // TODO add your handling code here:
            
            String n="";
            Myconnection1();
            String room =txtroom.getSelectedItem().toString();
            String m="SELECT `availity` FROM `room` WHERE `room_no`='"+room+"'";
            
            rs=st.executeQuery(m);
            while(rs.next()){
                n=rs.getString(1);
                
               
            }
            if(n.contains("Ocupied")){
                    JOptionPane.showMessageDialog(this, "Sorry!this room isn't available.");
                }
        } catch (SQLException ex) {
            Logger.getLogger(Cutomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_txtroomPopupMenuWillBecomeInvisible

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // TODO add your handling code here:
        
        
      
    }//GEN-LAST:event_txtidKeyTyped

    private void txtmobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobileKeyTyped
        // TODO add your handling code here:
          char i=evt.getKeyChar();
        if(!(Character.isDigit(i)) ){
            evt.consume();
        }
    }//GEN-LAST:event_txtmobileKeyTyped

    
    
    
    
    /**
     * @param args the command line arguments
     */
   
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cutomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cutomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cutomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cutomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cutomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date1;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jhjhjk;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton others;
    private javax.swing.JComboBox txtcheck;
    private javax.swing.JTextField txtcountry;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdep;
    private javax.swing.JTextField txtid;
    private javax.swing.JComboBox txtidname;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtname;
    private javax.swing.JComboBox txtroom;
    // End of variables declaration//GEN-END:variables
}
