/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManage;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mizanur Rahman
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_male_user_50px.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 80, 100, 60);

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(85, 17, 102));
        jLabel4.setText("enter your password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 250, 110, 20);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_hide_20px_4.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 270, 34, 40);

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 17, 102));
        jLabel6.setText("enter your name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 160, 90, 20);

        jButton1.setBackground(new java.awt.Color(85, 17, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 380, 90, 23);

        jButton2.setBackground(new java.awt.Color(85, 17, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 380, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("or");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 370, 34, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_male_user_20px_1.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 180, 20, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_password_20px_1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 280, 40, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/icons8_cancel_20px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 0, 20, 20);

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 17, 102)));
        txtname.setCaretColor(new java.awt.Color(255, 255, 255));
        txtname.setOpaque(false);
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(110, 180, 240, 40);

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(85, 17, 102)));
        txtpass.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpass.setOpaque(false);
        getContentPane().add(txtpass);
        txtpass.setBounds(110, 270, 240, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HotelManage/Picture/Essque-Zalu-Zanzibar-Resort.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 520);

        setSize(new java.awt.Dimension(426, 517));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            MyConnection mc=new MyConnection();
            mc.Myconnect();
            String name=txtname.getText().toString();
            String pass =txtpass.getText().toString();
            String m="SELECT `name`,`password`FROM `admin`WHERE `name`=? AND `password`=?";
            mc.pst=mc.con.prepareStatement(m);
            mc.pst.setString(1, name);
            mc.pst.setString(2,pass);
            mc.rs=mc.pst.executeQuery();
            if(mc.rs.next()){
              String n=mc.rs.getString(1);
              String v=mc.rs.getString(2);
              if(name.contains(n) && pass.contains(v)){
                  this.dispose();
                  new Home().setVisible(true);
              }
              else{
                  JOptionPane.showMessageDialog(this, "Wrong!Your name or Password is not correct");
              }
             
            }
             else{
                  JOptionPane.showMessageDialog(this, "Wrong!Your name or Password is not correct");
                  
              }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    int count=0;
    String [] imagename={"icons8_eye_20px_4.png","icons8_hide_20px_4.png","icons8_eye_20px_4.png","icons8_hide_20px_4.png","icons8_eye_20px_4.png","icons8_hide_20px_4.png"};
    
    void ViewIconSet(){
        
         ImageIcon[] ic=new ImageIcon[6];
        for (int i = 0; i < ic.length; i++) {
           // ImageIcon imageIcon = ic[i];
            
        
        ic [i]=new ImageIcon(getClass().getResource("/HotelManage/Picture/"+imagename[i]));
        }
        //setIcon(iic);
        if(count<ic.length)
        {
            jLabel8.setIcon(ic[count]);
            count++;
            if(count==1){
               txtpass.setEchoChar((char)0);
           }
            else if(count==2){
               txtpass.setEchoChar('*'); 
            }
             else if(count==3){
               txtpass.setEchoChar((char)0); 
            }
              else if(count==4){
               txtpass.setEchoChar('*'); 
            }
              else if(count==5){
               txtpass.setEchoChar((char)0); 
            }
           else{
               txtpass.setEchoChar('*');
           }
        }
        
    }
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
         ViewIconSet();
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtpass.requestFocus();
        }
    }//GEN-LAST:event_txtnameKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new Signup_mini().setVisible(true);
        this.dispose();
        //new Login().setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
